name: $name
shortname: $shortname
author: $author
email: $email
domain: $domain
google_id: $google_id

markdown: redcarpet
pygments: true
paginate: 5
permalink: none

tabs:
  - title: Posts
    url: /
