name: The Nutils Project
shortname: Nutils
author: Nutils
email: gertjanvanzwieten@gmail.com
domain: nutils.org
google_id: UA-45178960-1
github: nutils

markdown: redcarpet
pygments: true
paginate: 5

tabs:
  - title: Home
    url: /
  - title: Gallery
    url: /gallery.html
#  - title: Docs
#    url: /docs.html
#  - title: News
#    url: /news.html
#  - title: About
#    url: /about.html

scripts: google_analytics
