name: The Nutils Project
shortname: Nutils
author: Nutils
email: info@nutils.org
domain: www.nutils.org
google_id: UA-45178960-1
github: nutils

gems: [jekyll-paginate]
paginate: 5
paginate_path: "news/page:num/"

tabs:
  - title: Home
    url: /
  - title: Gallery
    url: /gallery.html
  - title: News
    url: /news
  - title: Docs
    url: http://docs.nutils.org
  - title: Github
    url: http://github.com/nutils

scripts: google_analytics
